# Generated by Django 2.2.2 on 2020-04-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue_System',
            fields=[
                ('queue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('queue_no', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.IntegerField(max_length=255)),
                ('app_time', models.TimeField()),
                ('me_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Medical_Personal')),
                ('pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Patient')),
            ],
        ),
    ]
