# Generated by Django 2.2.2 on 2020-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_system',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queue_system',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
