# Generated by Django 2.2.2 on 2020-04-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_auto_20200427_0148'),
        ('queuesystem', '0002_auto_20200427_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_system',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.Patient'),
        ),
    ]
