# Generated by Django 2.2.2 on 2020-04-26 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queuesystem', '0003_queue_system_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue_system',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Patient'),
        ),
    ]
