# Generated by Django 2.2.2 on 2020-04-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queuesystem', '0004_auto_20200427_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
    ]
