# Generated by Django 2.2.2 on 2020-04-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_auto_20200427_0148'),
        ('queuesystem', '0005_delete_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('create_date', models.DateField(auto_now=True)),
                ('next_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('me_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Medical_Personal')),
                ('pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.Patient')),
            ],
        ),
    ]
