# Generated by Django 2.2.2 on 2020-04-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_auto_20200427_0414'),
        ('queuesystem', '0008_remove_queue_system_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue_system',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.Medical_Personal'),
        ),
    ]
