# Generated by Django 2.2.2 on 2020-04-23 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Personal',
            fields=[
                ('position', models.CharField(max_length=255)),
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('national_id', models.CharField(max_length=13, unique=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('name_title', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('blood_type', models.CharField(max_length=3)),
                ('address', models.TextField()),
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
