# Generated by Django 2.2.2 on 2020-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20200422_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_personal',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
    ]
