# Generated by Django 2.2.2 on 2020-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20200426_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_personal',
            name='picture',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
