# Generated by Django 2.2.2 on 2020-04-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_auto_20200426_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_personal',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='picture',
        ),
    ]
