# Generated by Django 2.2.2 on 2020-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_auto_20200426_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_personal',
            name='picture',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
